/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rentalmobil;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author mochd
 */
public class Data_Transaksi extends javax.swing.JFrame {
public Connection conn;
    public Statement cn;
    private DefaultTableModel transaksi;
    public boolean databaru;
    /**
     * Creates new form Transaksi
     */
    public void koneksi(){
 try{
    Class.forName("com.mysql.jdbc.Driver");
    conn = DriverManager.getConnection("jdbc:mysql://localhost/rental_mobil","root","");
    cn = conn.createStatement();
 }catch (Exception e){
     JOptionPane.showMessageDialog(this,"koneksi gagal..", "Error",JOptionPane.ERROR_MESSAGE);
 
System.out.println(e.getMessage());
 
}
}
    public void bersih(){
    txt_id.setText("");
    txt_pelanggan_tf.setText("");
    txt_tf.setText("");
    txt_tgl.setText("");
    txt_idmobil.setText("");
    txt_merkmobil.setText("");
    txt_harga.setText("");
    txt_hari.setText("");

 
}
    public void tampildata(){
             transaksi = new DefaultTableModel ( );
             Tabel_Transaksi.setModel(transaksi);
             transaksi.addColumn("IDPelanggan");
             transaksi.addColumn("Nama Pelanggan");
             transaksi.addColumn("No Transaksi");
             transaksi.addColumn("Tanggal");
             transaksi.addColumn("ID Mobil");
             transaksi.addColumn("Merk");
             transaksi.addColumn("Harga");
             transaksi.addColumn("Jumlah Hari");
 
try{
koneksi();
    String sql = "Select * from transaksi order by NAMAPEL asc";
    ResultSet rs = cn.executeQuery(sql);
while (rs.next())
 
{
transaksi.addRow(new Object[]{
rs.getString(1),
rs.getString(2),
rs.getString(3),
rs.getString(4),
rs.getString(5),
rs.getString(6),
rs.getString(7),
rs.getString(8),
});
}
Tabel_Transaksi.setModel(transaksi);
}catch (Exception e)
{
JOptionPane.showMessageDialog(null, "Ada Kesalahan");
 
}
 
}
    public Data_Transaksi() {
        initComponents();
         transaksi = new DefaultTableModel ( );
             Tabel_Transaksi.setModel(transaksi);
             transaksi.addColumn("IDPelanggan");
             transaksi.addColumn("Nama Pelanggan");
             transaksi.addColumn("No Transaksi");
             transaksi.addColumn("Tanggal");
             transaksi.addColumn("ID Mobil");
             transaksi.addColumn("Merk");
             transaksi.addColumn("Harga");
             transaksi.addColumn("Jumlah Hari");
               getData(); 
    }
    public void getData(){
     
     transaksi.getDataVector( ).removeAllElements( );
     transaksi.fireTableDataChanged( );


     try{
           
           Statement stat = (Statement)koneksi.getKoneksi().createStatement();
           String sql        = "Select * from transaksi";
           ResultSet res   = stat.executeQuery(sql);

           
           while(res.next ()){
                Object[ ] obj = new Object[8];
                obj[0] = res.getString("id_pelanggan"); 
                obj[1] = res.getString("nama_pelanggan");
                obj[2] = res.getString("no_transaksi"); 
                obj[3] = res.getString("tanggal");
                obj[4] = res.getString("id_mobil"); 
                obj[5] = res.getString("merk");
                obj[6] = res.getString("harga"); 
                obj[7] = res.getString("jumlah_hari");
                
             

                transaksi.addRow(obj);
            }
      }catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
      }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_tgl = new javax.swing.JTextField();
        txt_merkmobil = new javax.swing.JTextField();
        txt_idmobil = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        txt_hari = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_tf = new javax.swing.JTextField();
        txt_pelanggan_tf = new javax.swing.JTextField();
        txt_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabel_Transaksi = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_bayar = new javax.swing.JTextField();
        btn_ubah1 = new javax.swing.JButton();
        btn_ubah2 = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        btn_harga = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSAKSI RENTAL MOBIL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(314, 314, 314)
                .addComponent(jLabel1)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Tanggal :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Jumlah Hari");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Harga");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Merk");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("ID Mobil");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("No Transaksi :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("ID Pelanggan :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Nama Pelanggan :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(txt_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(txt_pelanggan_tf))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_pelanggan_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        Tabel_Transaksi.setBackground(new java.awt.Color(204, 204, 204));
        Tabel_Transaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        Tabel_Transaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(Tabel_Transaksi);

        jButton1.setBackground(new java.awt.Color(0, 204, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Simpan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btn_ubah.setBackground(new java.awt.Color(0, 204, 51));
        btn_ubah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Total Bayar :");

        txt_bayar.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_bayar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btn_ubah1.setBackground(new java.awt.Color(0, 204, 51));
        btn_ubah1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah1.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah1.setText("Hapus");
        btn_ubah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah1ActionPerformed(evt);
            }
        });

        btn_ubah2.setBackground(new java.awt.Color(0, 204, 51));
        btn_ubah2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_ubah2.setForeground(new java.awt.Color(255, 255, 255));
        btn_ubah2.setText("Clear");
        btn_ubah2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah2ActionPerformed(evt);
            }
        });

        btn_menu.setBackground(new java.awt.Color(204, 204, 204));
        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_menu.setText("MENU");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_harga.setBackground(new java.awt.Color(0, 204, 51));
        btn_harga.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_harga.setForeground(new java.awt.Color(255, 255, 255));
        btn_harga.setText("HARGA ");
        btn_harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hargaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_idmobil, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txt_merkmobil, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txt_hari, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_ubah2)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_ubah1))
                                    .addComponent(btn_harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_ubah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton1))
                                    .addComponent(btn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_idmobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_merkmobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(btn_ubah)
                            .addComponent(btn_ubah1)
                            .addComponent(btn_ubah2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_harga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(251, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         String id_tf = txt_id.getText();
    String nama_pel = txt_pelanggan_tf.getText();
    String noTransaksi = txt_tf.getText();
    String tanggal = txt_tgl.getText();
    String idmobil = txt_idmobil.getText();
    String merk = txt_merkmobil.getText();
    String harga = txt_harga.getText();
    String jumlahhari = txt_hari.getText();

    // Validasi inputan (opsional)
    if (id_tf.isEmpty() || nama_pel.isEmpty() || noTransaksi.isEmpty() || tanggal.isEmpty()|| 
            idmobil.isEmpty()||merk.isEmpty()|| harga.isEmpty()|| jumlahhari.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isi semua kolom!");
        return;
    }

    // Tambahkan data ke tabel
    DefaultTableModel model = (DefaultTableModel) Tabel_Transaksi.getModel();
    model.addRow(new Object[]{id_tf, nama_pel,noTransaksi, tanggal, idmobil, merk, harga, jumlahhari}); // Sesuaikan nama kolom dan data yang disimpan

    // Bersihkan inputan setelah ditambahkan
    txt_id.setText("");
    txt_pelanggan_tf.setText("");
    txt_tf.setText("");
    txt_tgl.setText("");
    txt_idmobil.setText("");
    txt_merkmobil.setText("");
    txt_harga.setText("");
    txt_hari.setText("");
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         // Ambil indeks baris yang dipilih
    int selectedRow = Tabel_Transaksi.getSelectedRow();

    // Validasi apakah baris dipilih
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus!");
        return;
    }

    // Konfirmasi pengguna untuk menghapus data
    int option = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
    if (option == JOptionPane.YES_OPTION) {
        // Hapus data dari tabel
        DefaultTableModel model = (DefaultTableModel) Tabel_Transaksi.getModel();
        model.removeRow(selectedRow);

        // Bersihkan inputan setelah dihapus (opsional)
       txt_id.setText("");
    txt_pelanggan_tf.setText("");
    txt_tf.setText("");
    txt_tgl.setText("");
    txt_idmobil.setText("");
    txt_merkmobil.setText("");
    txt_harga.setText("");
    txt_hari.setText("");
    }                                        
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        txt_id.setText("");
    txt_pelanggan_tf.setText("");
    txt_tf.setText("");
    txt_tgl.setText("");
    txt_idmobil.setText("");
    txt_merkmobil.setText("");
    txt_harga.setText("");
    txt_hari.setText("");
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // Ambil indeks baris yang dipilih
    int selectedRow = Tabel_Transaksi.getSelectedRow();

    // Validasi apakah baris dipilih
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan diubah!");
        return;
    }

    // Ambil data dari inputan
    String id_tf = txt_id.getText();
    String nama_pel = txt_pelanggan_tf.getText();
    String noTransaksi = txt_tf.getText();
    String tanggal = txt_tgl.getText();
    String idmobil = txt_idmobil.getText();
    String merk = txt_merkmobil.getText();
    String harga = txt_harga.getText();
    String jumlahhari = txt_hari.getText();

    // Validasi inputan (opsional)
    if (id_tf.isEmpty() || nama_pel.isEmpty() || noTransaksi.isEmpty() || tanggal.isEmpty()|| 
            idmobil.isEmpty()||merk.isEmpty()|| harga.isEmpty()|| jumlahhari.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isi semua kolom!");
        return;
    }

    // Perbarui data pada tabel
    DefaultTableModel model = (DefaultTableModel) Tabel_Transaksi.getModel();
    model.setValueAt(id_tf, selectedRow, 0); // Ganti indeks kolom sesuai dengan struktur tabel
    model.setValueAt(nama_pel, selectedRow, 1);
    model.setValueAt(noTransaksi, selectedRow, 2);
    model.setValueAt(tanggal, selectedRow, 3);
    model.setValueAt(idmobil, selectedRow, 4);
    model.setValueAt(merk, selectedRow, 5);
    model.setValueAt(harga, selectedRow, 6);
    model.setValueAt(jumlahhari, selectedRow, 7);

    // Bersihkan inputan setelah diubah
    txt_id.setText("");
    txt_pelanggan_tf.setText("");
    txt_tf.setText("");
    txt_tgl.setText("");
    txt_idmobil.setText("");
    txt_merkmobil.setText("");
    txt_harga.setText("");
    txt_hari.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
         // Ambil indeks baris yang dipilih
    int selectedRow = Tabel_Transaksi.getSelectedRow();

    // Validasi apakah baris dipilih
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan diubah!");
        return;
    }

    // Ambil data dari inputan
   String id_tf = txt_id.getText();
    String nama_pel = txt_pelanggan_tf.getText();
    String noTransaksi = txt_tf.getText();
    String tanggal = txt_tgl.getText();
    String idmobil = txt_idmobil.getText();
    String merk = txt_merkmobil.getText();
    String harga = txt_harga.getText();
    String jumlahhari = txt_hari.getText();

    // Validasi inputan (opsional)
    if (id_tf.isEmpty() || nama_pel.isEmpty() || noTransaksi.isEmpty() || tanggal.isEmpty()|| 
            idmobil.isEmpty()||merk.isEmpty()|| harga.isEmpty()|| jumlahhari.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Isi semua kolom!");
        return;
    }

    // Perbarui data pada tabel
    DefaultTableModel model = (DefaultTableModel) Tabel_Transaksi.getModel();
     model.setValueAt(id_tf, selectedRow, 0); // Ganti indeks kolom sesuai dengan struktur tabel
    model.setValueAt(nama_pel, selectedRow, 1);
    model.setValueAt(noTransaksi, selectedRow, 2);
    model.setValueAt(tanggal, selectedRow, 3);
    model.setValueAt(idmobil, selectedRow, 4);
    model.setValueAt(merk, selectedRow, 5);
    model.setValueAt(harga, selectedRow, 6);
    model.setValueAt(jumlahhari, selectedRow, 7);
    // Bersihkan inputan setelah diubah
    txt_id.setText("");
    txt_pelanggan_tf.setText("");
    txt_tf.setText("");
    txt_tgl.setText("");
    txt_idmobil.setText("");
    txt_merkmobil.setText("");
    txt_harga.setText("");
    txt_hari.setText("");
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_ubah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah1ActionPerformed
        // Ambil indeks baris yang dipilih
    int selectedRow = Tabel_Transaksi.getSelectedRow();

    // Validasi apakah baris dipilih
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus!");
        return;
    }

    // Konfirmasi pengguna untuk menghapus data
    int option = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    
    if (option == JOptionPane.YES_OPTION) {
        // Hapus data dari tabel
        DefaultTableModel model = (DefaultTableModel) Tabel_Transaksi.getModel();
        model.removeRow(selectedRow);

        // Bersihkan inputan setelah dihapus (opsional)
       txt_id.setText("");
        txt_pelanggan_tf.setText("");
        txt_tf.setText("");
        txt_tgl.setText("");
        txt_idmobil.setText("");
        txt_merkmobil.setText("");
        txt_harga.setText("");
        txt_hari.setText("");
    }                
    }//GEN-LAST:event_btn_ubah1ActionPerformed

    private void btn_ubah2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah2ActionPerformed
        txt_id.setText("");
        txt_pelanggan_tf.setText("");
        txt_tf.setText("");
        txt_tgl.setText("");
        txt_idmobil.setText("");
        txt_merkmobil.setText("");
        txt_harga.setText("");
        txt_hari.setText("");
    }//GEN-LAST:event_btn_ubah2ActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
       Menu form1= new Menu();
                    form1.setVisible(true);
                    this.setVisible(false);
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hargaActionPerformed
     
    try {
        // Ambil nilai harga dan jumlah hari dari JTextField
        double harga = Double.parseDouble(txt_harga.getText());
        int jumlahHari = Integer.parseInt(txt_hari.getText());

        // Hitung total bayar
        double totalBayar = harga * jumlahHari;

        // Tampilkan hasil di JTextField
        txt_bayar.setText(String.valueOf(totalBayar));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Masukkan nilai yang valid untuk harga dan jumlah hari.");
    }

    }//GEN-LAST:event_btn_hargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_Transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabel_Transaksi;
    private javax.swing.JButton btn_harga;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton btn_ubah1;
    private javax.swing.JButton btn_ubah2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt_bayar;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_hari;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_idmobil;
    private javax.swing.JTextField txt_merkmobil;
    private javax.swing.JTextField txt_pelanggan_tf;
    private javax.swing.JTextField txt_tf;
    private javax.swing.JTextField txt_tgl;
    // End of variables declaration//GEN-END:variables

    private void exportAllTableDataToTextFile(JTable Tabel_Transaksi) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
